version: '3.8'

services:
  # BackstopJS.
  backstop:
    image: backstopjs/backstopjs:4.5.0
    volumes:
      - ./:/src
    depends_on:
      - web
    shm_size: 1gb
    entrypoint: [backstop, --config=/src/backstopjs/backstop.js]

  # Static file server.
  web:
    image: nginx:stable-alpine
    volumes:
      - ./upgrade/public:/usr/share/nginx/html
    ports:
      - "8080:80"
